<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ThushDee-DELL" failures="3" tests="14" name="Test" time="23.303" errors="0" timestamp="2024-03-29T17:51:06 IST">
  <testcase classname="api.test.UserTests" name="testPostUser" time="2.643"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.296"/>
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="2.611"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.234"/>
  <testcase classname="api.test.UserTests2" name="testPostUser" time="1.222"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.294"/>
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="2.559"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.299"/>
  <testcase classname="api.test.DDTests" name="testPostuser" time="1.235"/>
  <testcase classname="api.test.DDTests" name="testPostuser" time="1.288"/>
  <testcase classname="api.test.DDTests" name="testPostuser" time="1.257"/>
  <testcase classname="api.test.DDTests" name="testDeleteuserByName" time="1.278">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteuserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteuserByName -->
  <testcase classname="api.test.DDTests" name="testDeleteuserByName" time="1.312">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteuserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteuserByName -->
  <testcase classname="api.test.DDTests" name="testDeleteuserByName" time="1.27">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteuserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteuserByName -->
</testsuite> <!-- Test -->
